### ISSUE TITLE
CSS3 Color Keywords in *.css Files Are Not Highlighted Consistently

### ISSUE THREAD

**Issue by patrickdark** [SublimeTextIssues/DefaultPackages#84]
Consider these CSS3 Color module keywords in Sublime Text 3 Build 3065 using the Monokai theme:

```CSS
* {
	color: currentcolor;
	color: aliceblue;
	color: antiquewhite;
	color: aqua;
	color: aquamarine;
	color: azure;
	color: beige;
	color: bisque;
	color: black;
	color: blanchedalmond;
	color: blue;
	color: blueviolet;
	color: brown;
	color: burlywood;
	color: cadetblue;
	color: chartreuse;
	color: chocolate;
	color: coral;
	color: cornflowerblue;
	color: cornsilk;
	color: crimson;
	color: cyan;
	color: darkblue;
	color: darkcyan;
	color: darkgoldenrod;
	color: darkgray;
	color: darkgreen;
	color: darkgrey;
	color: darkkhaki;
	color: darkmagenta;
	color: darkolivegreen;
	color: darkorange;
	color: darkorchid;
	color: darkred;
	color: darksalmon;
	color: darkseagreen;
	color: darkslateblue;
	color: darkslategray;
	color: darkslategrey;
	color: darkturquoise;
	color: darkviolet;
	color: deeppink;
	color: deepskyblue;
	color: dimgray;
	color: dimgrey;
	color: dodgerblue;
	color: firebrick;
	color: floralwhite;
	color: forestgreen;
	color: fuchsia;
	color: gainsboro;
	color: ghostwhite;
	color: gold;
	color: goldenrod;
	color: gray;
	color: green;
	color: greenyellow;
	color: grey;
	color: honeydew;
	color: hotpink;
	color: indianred;
	color: indigo;
	color: ivory;
	color: khaki;
	color: lavender;
	color: lavenderblush;
	color: lawngreen;
	color: lemonchiffon;
	color: lightblue;
	color: lightcoral;
	color: lightcyan;
	color: lightgoldenrodyellow;
	color: lightgray;
	color: lightgreen;
	color: lightgrey;
	color: lightpink;
	color: lightsalmon;
	color: lightseagreen;
	color: lightskyblue;
	color: lightslategray;
	color: lightslategrey;
	color: lightsteelblue;
	color: lightyellow;
	color: lime;
	color: limegreen;
	color: linen;
	color: magenta;
	color: maroon;
	color: mediumaquamarine;
	color: mediumblue;
	color: mediumorchid;
	color: mediumpurple;
	color: mediumseagreen;
	color: mediumslateblue;
	color: mediumspringgreen;
	color: mediumturquoise;
	color: mediumvioletred;
	color: midnightblue;
	color: mintcream;
	color: mistyrose;
	color: moccasin;
	color: navajowhite;
	color: navy;
	color: oldlace;
	color: olive;
	color: olivedrab;
	color: orange;
	color: orangered;
	color: orchid;
	color: palegoldenrod;
	color: palegreen;
	color: paleturquoise;
	color: palevioletred;
	color: papayawhip;
	color: peachpuff;
	color: peru;
	color: pink;
	color: plum;
	color: powderblue;
	color: purple;
	color: red;
	color: rosybrown;
	color: royalblue;
	color: saddlebrown;
	color: salmon;
	color: sandybrown;
	color: seagreen;
	color: seashell;
	color: sienna;
	color: silver;
	color: skyblue;
	color: slateblue;
	color: slategray;
	color: slategrey;
	color: snow;
	color: springgreen;
	color: steelblue;
	color: tan;
	color: teal;
	color: thistle;
	color: tomato;
	color: turquoise;
	color: violet;
	color: wheat;
	color: white;
	color: whitesmoke;
	color: yellow;
	color: yellowgreen;
}
```

The vast majority of these keywords are displayed in white with a purple background. The apparent default color for CSS keywords in this theme should be cyan.

The currentcolor keyword also appears differently; it appears in the default color (white).

Please make the theme colors consistent.
